name: cd

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: install npm
        run: npm install
      -
        name: run webpack
        run: npm run build-docker
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/garager:${{ github.workflow }}${{ github.run_number }}
      -
        name: SSH
        uses: appleboy/ssh-action@master
        env:
          TAGNAME: ${{ github.workflow }}${{ github.run_number }}
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          envs: TAGNAME
          script: |
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -q)
            docker pull "joemitz/garager:$TAGNAME"
            docker run -p 80:3000 -d \
            --env AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
            --env AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            --env RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            --env STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            --env MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} \
            "joemitz/garager:$TAGNAME"
