name: ci

on:
  push:
    branches:
      - main
      - '*'

  workflow_dispatch:

jobs:
  eslint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
  build:
      runs-on: ubuntu-latest

      steps:
        -
          name: Test code
          uses: actions/checkout@v2
        -
          name: Install packages
          run: npm ci
        -
          name: Run Tests
          run: npm run ci:test
        -
         name: Run ESLint
         run: eslint . --ext .js,.jsx
