name: ci

on:
  push:
    branches:
      - main
      - '*'

  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        -
          name: Test code
          uses: actions/checkout@v2
        -
          name: Create env file
          run: touch .env
        - 
          name: Add RDS password
          run: echo RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} >> .env
        -
          name: Install packages
          run: npm install -f
        -
          name: Run Tests
          run: npm run ci:test
        -
          name: Run ESLint
          run: npm run lint

