name: ci

on:
  push:
    branches:
      - main
      - '*'

  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        -
          name: Test code
          uses: actions/checkout@v2
        -
          name: Run ESLint
          run: npm run lint
        -
          name: Install packages
          run: npm ci
        -
          name: Run Tests
          run: npm run ci:test
        -
          name: Install modules
          run: yarn

